"""
gnn_warm_start.py
Graph Neural Network predictor for warm-starting the MIP solver.

Research Basis
--------------
Improvement 5 from research_improvements.md:
    "Accelerating Mixed Integer Programs for Disaster Relief
     using Graph Neural Network Warm-Starts"

Method
------
A simple 2-layer Graph Convolutional Network (GCN) takes the district
graph as input and predicts the optimal number of truck/UAV trips per
district.  These predicted values are fed to the MIP solver as an initial
warm-start, replacing the naive "previous-solution" cache and drastically
reducing CBC branch-and-bound search time on large instances.

Graph Construction
------------------
  Nodes = districts (feature vector: inventory, dep_time, demand, shortage,
                      demand_std, dep_cost_weight)
  Edges = fully connected, weighted by inverse Haversine distance.

Training
--------
Supervised on a history of stored MIP solutions (generated by running the
cold MIPSolver for a few hundred episodes and logging the optimal solutions).
"""

from __future__ import annotations

import math
import numpy as np
from typing import Dict, List, Optional, Tuple

try:
    import torch
    import torch.nn as nn
    import torch.optim as optim
    TORCH_AVAILABLE = True
except ImportError:
    TORCH_AVAILABLE = False

from app.ml.mdp import MDPState, DistrictState
from app.ml.deprivation import marginal_deprivation_cost


# ── Geometry helper ───────────────────────────────────────────────────────────

def _haversine_km(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    R = 6_371.0
    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)
    a = (math.sin(dlat / 2) ** 2
         + math.cos(math.radians(lat1))
         * math.cos(math.radians(lat2))
         * math.sin(dlon / 2) ** 2)
    return 2 * R * math.asin(math.sqrt(max(0.0, a)))


# ── GCN Layers ────────────────────────────────────────────────────────────────

if TORCH_AVAILABLE:
    class GraphConvLayer(nn.Module):
        """
        Simple symmetric graph convolution:
            H' = ReLU( D^{-1/2} A D^{-1/2} H W )

        For efficiency, the adjacency matrix is passed as a dense tensor.
        """

        def __init__(self, in_dim: int, out_dim: int):
            super().__init__()
            self.linear = nn.Linear(in_dim, out_dim, bias=True)
            self.act    = nn.ReLU()

        def forward(
            self,
            H:   "torch.Tensor",   # (N, in_dim)
            adj: "torch.Tensor",   # (N, N) adjacency / weight matrix
        ) -> "torch.Tensor":
            # Normalise adjacency
            deg       = adj.sum(dim=1, keepdim=True).clamp(min=1.0)
            adj_norm  = adj / deg
            agg       = adj_norm @ H          # (N, in_dim)
            return self.act(self.linear(agg)) # (N, out_dim)

    class GNNModel(nn.Module):
        """
        2-layer GCN with separate regression heads for trucks and UAVs.

        Output: [truck_trips_n, uav_trips_n] per district (continuous,
                converted to int in generate_warm_start).
        """

        def __init__(self, node_feat_dim: int, hidden_dim: int = 16):
            super().__init__()
            self.conv1 = GraphConvLayer(node_feat_dim, hidden_dim)
            self.conv2 = GraphConvLayer(hidden_dim,    hidden_dim)
            self.truck_head = nn.Linear(hidden_dim, 1)
            self.uav_head   = nn.Linear(hidden_dim, 1)
            self.relu        = nn.ReLU()

        def forward(
            self,
            node_feats: "torch.Tensor",  # (N, node_feat_dim)
            adj:        "torch.Tensor",  # (N, N)
        ) -> "Tuple[torch.Tensor, torch.Tensor]":
            h = self.conv1(node_feats, adj)
            h = self.conv2(h,          adj)
            truck_pred = self.relu(self.truck_head(h)).squeeze(-1)  # (N,)
            uav_pred   = self.relu(self.uav_head(h)).squeeze(-1)    # (N,)
            return truck_pred, uav_pred


# ── GNN Warm-Start Predictor ──────────────────────────────────────────────────

class GNNWarmStartPredictor:
    """
    Wraps `GNNModel` and provides a sklearn-style API compatible with
    MIPSolver's warm-start interface.

    Node feature vector per district (6 features):
        [inventory, deprivation_time, demand_estimate, shortage,
         demand_std, marginal_dep_cost]

    Parameters
    ----------
    n_districts : int  — number of district nodes.
    hidden_dim  : int  — GCN hidden dimension (default 16).
    n_layers    : int  — not used here (2 fixed layers in GNNModel) but
                         stored for config compatibility.
    """

    NODE_FEAT_DIM = 6

    def __init__(
        self,
        n_districts: int,
        hidden_dim:  int = 16,
        n_layers:    int = 2,
        lr:          float = 0.001,
    ):
        if not TORCH_AVAILABLE:
            raise ImportError("PyTorch is required for GNNWarmStartPredictor.")
        self.n_districts = n_districts
        self.hidden_dim  = hidden_dim
        self.lr          = lr
        self.model       = GNNModel(self.NODE_FEAT_DIM, hidden_dim)
        self.optimizer   = optim.Adam(self.model.parameters(), lr=lr)
        self.is_trained  = False

    # ── Graph construction ────────────────────────────────────────────────────

    def _build_adjacency(self, districts: List[DistrictState]) -> "torch.Tensor":
        """
        Fully-connected adjacency matrix weighted by 1/(dist_km + 1).
        Uses truck_cost as a distance proxy when lat/lon unavailable.
        """
        N = len(districts)
        adj = np.zeros((N, N), dtype=np.float32)
        for i in range(N):
            for j in range(N):
                if i == j:
                    adj[i, j] = 1.0
                else:
                    # Proxy: inverse cost distance
                    avg_cost = (districts[i].truck_cost + districts[j].truck_cost) / 2
                    adj[i, j] = 1.0 / (avg_cost + 1.0)
        return torch.FloatTensor(adj)

    def _build_node_features(self, districts: List[DistrictState]) -> "torch.Tensor":
        """Build (N, NODE_FEAT_DIM) feature matrix from district states."""
        feats = []
        for d in districts:
            feats.append([
                d.inventory,
                float(d.deprivation_time),
                d.demand_estimate,
                d.shortage,
                d.demand_std,
                marginal_deprivation_cost(d.deprivation_time),
            ])
        return torch.FloatTensor(feats)

    # ── Warm-start generation ─────────────────────────────────────────────────

    def generate_warm_start(self, state: MDPState) -> Dict[str, int]:
        """
        Predict optimal vehicle trip counts and return a warm-start dict
        compatible with MIPSolver._last_solution format.

        Returns
        -------
        dict: {y_truck_0: int, y_uav_0: int, y_truck_1: int, ...}
        """
        self.model.eval()
        with torch.no_grad():
            node_feats = self._build_node_features(state.districts)
            adj        = self._build_adjacency(state.districts)
            t_pred, u_pred = self.model(node_feats, adj)

        warm_start: Dict[str, int] = {}
        for i in range(len(state.districts)):
            warm_start[f"y_truck_{i}"] = max(0, int(round(t_pred[i].item())))
            warm_start[f"y_uav_{i}"]   = max(0, int(round(u_pred[i].item())))
        return warm_start

    # ── Training ──────────────────────────────────────────────────────────────

    def train_from_mip_history(
        self,
        history: List[Dict],
        n_epochs: int = 50,
    ) -> List[float]:
        """
        Supervised training on logged MIP solutions.

        Parameters
        ----------
        history : list of dicts, each containing:
            "state"    : MDPState
            "solution" : dict {y_truck_i: int, y_uav_i: int, ...}
        n_epochs : int

        Returns
        -------
        List of per-epoch MSE losses.
        """
        if not history:
            return []

        self.model.train()
        losses = []
        criterion = nn.MSELoss()

        for epoch in range(n_epochs):
            epoch_loss = 0.0
            for sample in history:
                state    = sample["state"]
                solution = sample["solution"]
                n        = len(state.districts)

                node_feats = self._build_node_features(state.districts)
                adj        = self._build_adjacency(state.districts)
                t_pred, u_pred = self.model(node_feats, adj)

                t_target = torch.FloatTensor([
                    float(solution.get(f"y_truck_{i}", 0)) for i in range(n)
                ])
                u_target = torch.FloatTensor([
                    float(solution.get(f"y_uav_{i}",   0)) for i in range(n)
                ])

                loss = criterion(t_pred, t_target) + criterion(u_pred, u_target)
                self.optimizer.zero_grad()
                loss.backward()
                self.optimizer.step()
                epoch_loss += loss.item()

            avg_loss = epoch_loss / max(1, len(history))
            losses.append(avg_loss)

        self.is_trained = True
        return losses

    def collect_mip_solution(
        self,
        state:    MDPState,
        solution: Dict[str, int],
    ) -> Dict:
        """
        Convenience method to format a MIP solution for the history buffer.

        Parameters
        ----------
        state    : MDPState at decision time.
        solution : {y_truck_i: int, y_uav_i: int} from MIPSolver._last_solution.

        Returns
        -------
        dict suitable for appending to the history list.
        """
        return {"state": state, "solution": solution}
